[package]
name = "featherimage"
version = "0.1.0"
authors = ["Dreamifi"]
edition = '2018'

[lib]
name = "featherimage"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.12.3"
features = ["extension-module"]